apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-dashboard
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: supplychain-dashboard
  template:
    metadata:
      labels:
        app: supplychain-dashboard
    spec:
      containers:
        - name: supplychain-dashboard
          image: wyvern101/supplychain-risk-dashboard:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 20